In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook as tqdm

c:\users\skrishnamurthy2\appdata\local\continuum\anaconda3\envs\tensorflow_3.5\lib\importlib\_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
c:\users\skrishnamurthy2\appdata\local\continuum\anaconda3\envs\tensorflow_3.5\lib\importlib\_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
c:\users\skrishnamurthy2\appdata\local\continuum\anaconda3\envs\tensorflow_3.5\lib\importlib\_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
sess = tf.Session()

In [ ]:
x = tf.placeholder(tf.float32, shape = [None, 3])
y_true = tf.constant([[0], [2]], dtype=tf.float32)
linear_model = tf.layers.Dense(units=1)
y_pred = linear_model(x)

init = tf.global_variables_initializer()
sess.run(init)

In [ ]:
print(sess.run(y_pred, {x:[[1,2,3], [4,5,6]]}))

In [ ]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions = y_pred)
print(sess.run(loss, {x:[[1,2,3],[4,5,6]]}))

In [ ]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [ ]:
for i in range(100):
    _, loss_value = sess.run((train, loss), {x:[[1,2,3], [4,5,6]]})
    print(loss_value)

In [ ]:
r = tf.random_normal([10,3])
print(r)
dataset = tf.data.Dataset.from_tensor_slices(x)
print(dataset)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()
print(next_row)

linear_model = tf.layers.Dense(units=3)
# y_pred = linear_model()

In [6]:
# Define training and validation datasets with the same structure.
training_dataset = tf.data.Dataset.range(1000) #.map(
    #lambda x: x + tf.random_uniform([], -10, 10, tf.int64)).repeat()
validation_dataset = tf.data.Dataset.range(50)

# A feedable iterator is defined by a handle placeholder and its structure. We
# could use the `output_types` and `output_shapes` properties of either
# `training_dataset` or `validation_dataset` here, because they have
# identical structure.
handle = tf.placeholder(tf.string, shape=[])
iterator = tf.data.Iterator.from_string_handle(
    handle, training_dataset.output_types, training_dataset.output_shapes)
next_element = iterator.get_next()

# You can use feedable iterators with a variety of different kinds of iterator
# (such as one-shot and initializable iterators).
training_iterator = training_dataset.make_one_shot_iterator()
validation_iterator = validation_dataset.make_initializable_iterator()

# The `Iterator.string_handle()` method returns a tensor that can be evaluated
# and used to feed the `handle` placeholder.
training_handle = sess.run(training_iterator.string_handle())
validation_handle = sess.run(validation_iterator.string_handle())

# Loop forever, alternating between training and validation.
for _ in range(5):
  # Run 200 steps using the training dataset. Note that the training dataset is
  # infinite, and we resume from where we left off in the previous `while` loop
  # iteration.
  print("\nTraining Dataset: \n\n")
  for _ in range(200):
    print(sess.run(next_element, feed_dict={handle: training_handle}))
  
  print("\nValidation Dataset: \n\n")
  # Run one pass over the validation dataset.
  sess.run(validation_iterator.initializer)
  for _ in range(50):
    print(sess.run(next_element, feed_dict={handle: validation_handle}))


Training Dataset: 


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199

Validation Dataset: 


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

Training Dataset: 


200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
22

In [12]:
dataset = tf.data.Dataset.range(5)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

# Typically `result` will be the output of a model, or an optimizer's
# training operation.
result = tf.add(next_element, next_element)

sess.run(iterator.initializer)
print(sess.run(result))  # ==> "0"
print(sess.run(result))  # ==> "2"
print(sess.run(result))  # ==> "4"
print(sess.run(result))  # ==> "6"
print(sess.run(result))  # ==> "8"
try:
  sess.run(result)
except tf.errors.OutOfRangeError:
  print("End of dataset")  # ==> "End of dataset"

0
2
4
6
8
End of dataset


In [40]:
dataset1 = tf.data.Dataset.from_tensor_slices({'x1': tf.random_uniform([4,10])})
dataset2 = tf.data.Dataset.from_tensor_slices({'y': tf.random_uniform([4]), 'x2': tf.random_uniform([4,100])})
dataset3 = tf.data.Dataset.zip((dataset1, dataset2))

iterator = dataset3.make_initializable_iterator()

next1, (next2, next3) = iterator.get_next()
sess.run(iterator.initializer)
print(sess.run(next1))

{'x1': array([0.9775703 , 0.02017426, 0.17553031, 0.07655799, 0.55728483,
       0.4417392 , 0.8303379 , 0.82607174, 0.7066705 , 0.7749429 ],
      dtype=float32)}


In [54]:
x = tf.placeholder(tf.float32, shape=[4,10])
y = tf.placeholder(tf.float32, shape=[4])

x_data = tf.data.Dataset.from_tensor_slices(x)
y_data = tf.data.Dataset.from_tensor_slices(y)
z = tf.data.Dataset.zip((x_data, y_data))

iterator = z.make_initializable_iterator()

sess.run(iterator.initializer, 
         feed_dict={x:np.random.random_sample([4,10]), y:np.random.random_sample(4)})
while True:
    try:
        next_item = iterator.get_next()
        print(sess.run(next_item))
    except tf.errors.OutOfRangeError:
        print("End of Dataset")
        break

(array([0.46284986, 0.45027712, 0.94150215, 0.345851  , 0.98753583,
       0.99930453, 0.44107747, 0.05759045, 0.14981265, 0.65399307],
      dtype=float32), 0.44821918)
(array([0.74818426, 0.19512647, 0.8995081 , 0.9695794 , 0.62183315,
       0.11661623, 0.8494157 , 0.8214359 , 0.77490604, 0.53723663],
      dtype=float32), 0.5709294)
(array([0.2429206 , 0.0745701 , 0.17549615, 0.28771254, 0.6695717 ,
       0.3816504 , 0.82436717, 0.5676087 , 0.07056348, 0.3654402 ],
      dtype=float32), 0.24491805)
(array([0.08056088, 0.8394148 , 0.18472554, 0.05520961, 0.7729394 ,
       0.6166121 , 0.35959756, 0.76759386, 0.76012397, 0.86482424],
      dtype=float32), 0.09414565)
End of Dataset
